name: test
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    path-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
